apiVersion: apps/v1
kind: Deployment
metadata:
    name: events-app
    labels:
       app: events-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: events-app
    template:
        metadata:
            labels:
                app: events-app
        spec:
            containers:
              - name: events-app-container
                image: tantalor93/events-app
                imagePullPolicy: Always
                ports:
                - containerPort: 8080
                livenessProbe:
                  httpGet:
                    path: /actuator/info
                    port: 8080
                  initialDelaySeconds: 30
                  periodSeconds: 10
                readinessProbe:
                  httpGet:
                    path: /actuator/health
                    port: 8080
                  initialDelaySeconds: 30
                  periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: events-app
  labels:
    app: events-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: events-app
